In [68]:
import tensorflow as tf
import numpy as np

# **Creating tensor**

In [69]:
name_as_tensor = tf.Variable("Hossam", dtype=tf.string)
print(name_as_tensor)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hossam'>


In [70]:
vector = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=tf.float32)
print(vector)

tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(10,), dtype=float32)


In [71]:
vector = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=tf.float32)
print(vector)

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)>


In [72]:
tensor = tf.Variable(
    [[1, 2, 3, 4, 5,],
    [ 6, 7, 8, 9, 10]],
    dtype=tf.float32
  )
print(tensor)

<tf.Variable 'Variable:0' shape=(2, 5) dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]], dtype=float32)>


In [73]:
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], shape=(2, 5), dtype=tf.float32)
print(tensor)

tf.Tensor(
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]], shape=(2, 5), dtype=float32)


In [74]:
vector = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], shape=(10, 1), dtype=tf.float32)
print(vector)

tf.Tensor(
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]], shape=(10, 1), dtype=float32)


In [75]:
tesor_of_complex = tf.Variable(
    [1 + 2j, 3 + 4j],
    dtype=tf.complex64)
print(tesor_of_complex)

<tf.Variable 'Variable:0' shape=(2,) dtype=complex64, numpy=array([1.+2.j, 3.+4.j], dtype=complex64)>


In [76]:
zeros_tensor = tf.zeros(shape=(2, 3), dtype=tf.float32)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [77]:
ones_tensor = tf.ones(shape=(2, 3), dtype=tf.float32)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [78]:
random_tensor = tf.random.uniform(shape=(5, 6), minval=2, maxval=10, dtype=tf.float32)
print(random_tensor)

tf.Tensor(
[[9.661092  6.1368856 3.7762337 3.2184706 9.512897  4.611844 ]
 [9.293702  6.6469164 6.5663576 8.465069  8.860989  9.221125 ]
 [4.49662   7.167794  2.769764  9.222777  4.461046  3.1460419]
 [6.4033976 8.812488  4.1587734 7.6271563 5.4333897 8.596092 ]
 [5.0747766 3.0857143 9.908979  8.426862  4.5949383 4.8121777]], shape=(5, 6), dtype=float32)


In [79]:
random_tensor = tf.random.normal(shape=(5, 6), stddev=6, dtype=tf.float32)
print(random_tensor)

tf.Tensor(
[[ 15.534506     0.18732935   4.270515     9.153158     8.019412
   -1.2756788 ]
 [ -1.6202211    0.87775576   0.91125464   0.57432693 -13.77227
   -4.2894034 ]
 [ -2.8917437    5.5669985   -9.373075    -2.7607625    0.55079925
    1.5327613 ]
 [ -9.059861     3.5630643    2.7099178    7.3513384   -3.4446995
    2.350908  ]
 [  0.27317628   1.4588217    4.611095     1.4722316   14.072569
   -3.9108062 ]], shape=(5, 6), dtype=float32)


In [80]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.float32)
tensor_from_array = tf.constant(array, dtype=tf.float32)
print(tensor_from_array)

tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(10,), dtype=float32)


In [81]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.float32)
tensor_from_array = tf.convert_to_tensor(array, dtype=tf.float32)
print(tensor_from_array)

tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(10,), dtype=float32)


In [82]:
tensor = tf.range(start=0, limit=50, delta=5, dtype=tf.float32)
print(tensor)

tf.Tensor([ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.], shape=(10,), dtype=float32)


In [83]:
tensor = tf.fill(dims=(5, 5), value=5)
print(tensor)

tf.Tensor(
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]], shape=(5, 5), dtype=int32)


In [84]:
tensor = tf.eye(num_rows=5, num_columns=5, dtype=tf.float32)
print(tensor)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [85]:
diag_vector = tf.constant([1, 2, 3], dtype=tf.float32)
diag_tensor = tf.linalg.diag(diag_vector)
print(diag_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


# **Basic Tensor Operations**

In [86]:
tensor_addation = tf.add([5, 2, 3], [1, 2, 3])
print(tensor_addation)

tf.Tensor([6 4 6], shape=(3,), dtype=int32)


In [87]:
square_tensor = tf.square(3)
print(square_tensor)

tf.Tensor(9, shape=(), dtype=int32)


In [88]:
summation_tensor = tf.reduce_sum([5, 2, 4])
print(summation_tensor)

tf.Tensor(11, shape=(), dtype=int32)


In [89]:
add_square_tensor = tf.add(tf.square(5), tf.square(2))
print(add_square_tensor)

add_square_tensor = tf.square(5) + tf.square(2)
print(add_square_tensor)

tf.Tensor(29, shape=(), dtype=int32)
tf.Tensor(29, shape=(), dtype=int32)


In [90]:
x = tf.constant([[1, 2, 3]], dtype=tf.float32)
print(x)
tensor = tf.squeeze(x, axis=0)
print(tensor)

tf.Tensor([[1. 2. 3.]], shape=(1, 3), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [91]:
tensor = tf.constant(
    [[1, 2, 3],
     [7, 2, 3]],
    dtype=tf.float32)

add_tensor = tf.add(tensor, 5)
print(add_tensor)

tf.Tensor(
[[ 6.  7.  8.]
 [12.  7.  8.]], shape=(2, 3), dtype=float32)


In [92]:
tensor = tf.constant(
    [[1, 2, 3],
     [7, 2, 3]],
    dtype=tf.float32)

square_tensor = tensor ** 2
print(square_tensor)

tf.Tensor(
[[ 1.  4.  9.]
 [49.  4.  9.]], shape=(2, 3), dtype=float32)


In [93]:
tensor1 = tf.constant(
    [[1, 2, 3],
     [7, 2, 3]],
    dtype=tf.float32)

tensor2 = tf.constant(
    [[1, 2, 3],
     [7, 2, 3]],
    dtype=tf.float32)

add_tensor = np.add(tensor1, tensor2)
print(add_tensor)
print()

sub_tensor = np.subtract(tensor1, tensor2)
print(sub_tensor)
print()

mul_tensor = np.multiply(tensor1, tensor2)
print(mul_tensor)
print()

div_tensor = np.divide(tensor1, tensor2)
print(div_tensor)

[[ 2.  4.  6.]
 [14.  4.  6.]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[ 1.  4.  9.]
 [49.  4.  9.]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [98]:
arr = np.ones([5, 5])
tensor = tf.multiply(arr, 5)
print(tensor)

tf.Tensor(
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]], shape=(5, 5), dtype=float64)


In [99]:
tensor_to_numpy = tensor.numpy()
print(tensor_to_numpy)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
